version: "3.7"

services:
  database: 
    image: postgres
    container_name: database_rentx_ignite
    restart: always
    ports: 
      - 5432:5432
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx
    volumes: 
      - pgdata:/data/postgres
  redis:
    image: redis:alpine
    container_name: redis_rentx_ignite
    ports:
      - 6379:6379
  app:
    build: .
    container_name: api_rentx_ignite
    ports: 
      - 3333:3333
      - 9229:9229 
    volumes:
      - .:/usr/app
    links:
      - database
      - redis
    depends_on: 
      - database
      - redis

volumes: 
  pgdata:
    driver: local
